In [8]:
import numpy as np



numeros=[2,4,8,16,32,64,128]

array_numeros= np.array(numeros)

array_numeros



<b> PAR ou IMPAR</b>

In [18]:
print(array_numeros %2 == 0)



[ True  True  True  True  True  True  True]


<b>FIltro CONdicional</b>

In [22]:
print( "Maiores que 20: ",array_numeros[array_numeros > 20])
print( "Pares: ",array_numeros[array_numeros % 2 ==0])
print("impares",array_numeros[array_numeros % 2 ==1])

Maiores que 20:  [ 32  64 128]
Pares:  [  2   4   8  16  32  64 128]
impares []


<h2>OPERAÇÕES COM ARRAYS</h2>

In [23]:
print(array_numeros)
print('soma',np.sum(array_numeros))
print('Média',np.mean(array_numeros))
print('Minimo',np.min(array_numeros))
print('Máximo',np.max(array_numeros))

[  2   4   8  16  32  64 128]
soma 254
Média 36.285714285714285
Minimo 2
Máximo 128


# LISTA DE EXERCÍCIOS


In [25]:
array_numeros= np.array([1,2,3,4,5])

print(array_numeros *2)
print(array_numeros +10)
print(array_numeros **2)


[ 2  4  6  8 10]
[11 12 13 14 15]
[ 1  4  9 16 25]


In [13]:
array_numeros = np.array([7.5, 8.0, 6.5, 9.0, 5.5])

print('Média',np.mean(array_numeros))
print('Máximo',np.max(array_numeros))
print('Mínimp',np.min(array_numeros))



Média 7.3
Máximo 9.0
Mínimp 5.5


In [3]:
import numpy as np

array_numeros= np.array([10,20,30,40,50])

print(array_numeros / np.max(array_numeros))






[0.2 0.4 0.6 0.8 1. ]


In [12]:
array_idade= np.array([15,18,22,17,30,16])

print('Maiores de idade',array_idade[array_idade >= 18])

Maiores de idade [18 22 30]


In [45]:
import numpy as np
array_numeros= np.array([5,10,15,20,25,30])

print(array_numeros[(array_numeros > 10) & (array_numeros < 25)])





[15 20]


In [44]:
array_numeros=np.array([4,6,7,5,8,3,9])

print(len(array_numeros[array_numeros >= 6]))
print(sum(array_numeros >= 6))


4
4


In [65]:
numeros = np.array( [1000,2000,3000,1500])

numeros[numeros < 2000] += 500

print(numeros)


[1500 2000 3000 2000]


In [94]:
precos = np.array([10, 20, 30, 40])

precos=precos*1.1

print(precos)

[11. 22. 33. 44.]


In [34]:
filtro =np.array([10, 20, 30, 40, 50])

filtro=filtro[filtro > 25]

print(np.mean(filtro))

40.0


In [47]:
salario=np.array([2000, 3000, 4000, 2500, 5000])
idade=np.array([18, 25, 30, 22, 40])

idade=idade > 25

salario=(salario[idade])

print(np.mean(salario))


4500.0


In [52]:
numeros=np.array([5, 7, 8, 4, 9])

print(np.where(numeros>=7))

(array([1, 2, 4]),)


In [56]:
numeros=np.arange(1,11)
print(numeros[numeros%2 ==0])

[ 2  4  6  8 10]


In [1]:
import numpy as np  # Importa a biblioteca NumPy, que é usada para trabalhar com arrays e operações numéricas

# Gera um array de 10 números inteiros aleatórios entre 0 e 100 (inclusive)
# np.random.randint(início, fim_exclusivo, tamanho)
array = np.random.randint(0, 101, 10)

# Calcula a média dos valores do array
# np.mean() retorna a média aritmética dos elementos
media = np.mean(array)

# Filtra apenas os valores maiores que a média
# A expressão (array > media) cria um array booleano
# Usar isso como índice retorna apenas os elementos que satisfazem a condição
valores_maiores = array[array > media]

# Exibe o array original
print("Array original:", array)

# Exibe a média calculada
print("Média:", media)

# Exibe os valores filtrados
print("Valores maiores que a média:", valores_maiores)


Array original: [78 81 24 46 48 86 78 26 18 21]
Média: 50.6
Valores maiores que a média: [78 81 86 78]


In [95]:
dados=np.array([5, 7, 8, 6, 4, 9, 10])

media=np.mean(dados) #calcular a media

print(np.sum(dados > media)) # conta quantos elementos estão acima da média, já que verdadeiro vale 1 e falso 0
print(len(dados[dados>media])) # Aqui ele está contandos elementos maiores que a media...




3
3
